# Starship設定
# https://starship.rs/config/

# プロンプトの設定
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_state\
$cmd_duration\
$line_break\
$character"""

# ディレクトリ表示
[directory]
truncation_length = 3
truncate_to_repo = false
format = "[$path]($style) "
style = "bold cyan"

# Git ブランチ
[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold purple"

# Git ステータス
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
untracked = "?"
style = "bold red"

# コマンド実行時間
[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "bold yellow"

# 文字（プロンプト記号）
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

# ユーザー名（rootの時のみ表示）
[username]
show_always = false
format = "[$user]($style) "
style_user = "bold yellow"
style_root = "bold red"

# ホスト名（SSH接続時のみ表示）
[hostname]
ssh_only = true
format = "[@$hostname]($style) "
style = "bold green"

# Python
[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "
style = "yellow bold"

# Node.js
[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "
style = "green bold"

# Rust
[rust]
format = "[$symbol($version )]($style)"
symbol = " "
style = "red bold"

# Go
[golang]
format = "[$symbol($version )]($style)"
symbol = " "
style = "cyan bold"

# 時刻（必要に応じて有効化）
[time]
disabled = true
format = '[$time]($style) '
style = "bold white"
time_format = "%T"
